# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishList',
            new_name='List',
        ),
    ]
