# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('dashboard', '0002_auto_20180720_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='added_by',
        ),
        migrations.AddField(
            model_name='list',
            name='added_by',
            field=models.ManyToManyField(related_name='added', to='login.User'),
        ),
    ]
