# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('dashboard', '0004_auto_20180720_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='add_by',
        ),
        migrations.AddField(
            model_name='list',
            name='addtolist_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='addedtolist', to='login.User'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='list',
            name='added_by',
        ),
        migrations.AddField(
            model_name='list',
            name='added_by',
            field=models.ManyToManyField(related_name='added', to='login.User'),
        ),
        migrations.DeleteModel(
            name='Mylist',
        ),
    ]
